create table if not exists public.employees (
 id bigint generated by default as identity primary key,
 employee_no text unique not null,
 name text not null,
 department text,
 phone text,
 pin text not null,
 active boolean default true,
 created_at timestamptz default now()
);

create table if not exists public.orders (
 id bigint generated by default as identity primary key,
 employee_id bigint not null references public.employees(id) on delete cascade,
 order_date date not null,
 breakfast boolean default false,
 lunch boolean default false,
 dinner boolean default false,
 quantity integer not null default 1 check(quantity > 0),
 delivery boolean default false,
 status text default 'submitted',
 created_at timestamptz default now()
);

create table if not exists public.company_settings (
 id bigint generated by default as identity primary key,
 company_name text default 'Consarck Pvt Ltd',
 address text default 'Kuliyapitiya, Weralugama',
 phone text default '0763590747',
 email text,
 website text,
 logo_url text,
 meal_type text default 'Rice and Curry',
 order_closing_time time default '09:00'
);

create table if not exists public.admin_profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 display_name text,
 role text default 'admin'
);

alter table public.employees enable row level security;
alter table public.orders enable row level security;
alter table public.company_settings enable row level security;
alter table public.admin_profiles enable row level security;

-- For a first prototype. Tighten these policies before public production deployment.
create policy "employees read" on public.employees for select using (true);
create policy "employees insert" on public.employees for insert with check (true);
create policy "employees update" on public.employees for update using (true);

create policy "orders read" on public.orders for select using (true);
create policy "orders insert" on public.orders for insert with check (true);
create policy "orders update" on public.orders for update using (true);
create policy "orders delete" on public.orders for delete using (true);

create policy "settings read" on public.company_settings for select using (true);
create policy "settings insert" on public.company_settings for insert with check (true);
create policy "settings update" on public.company_settings for update using (true);

create policy "admin read" on public.admin_profiles for select using (true);

insert into public.company_settings(company_name,address,phone,meal_type)
select 'Consarck Pvt Ltd','Kuliyapitiya, Weralugama','0763590747','Rice and Curry'
where not exists(select 1 from public.company_settings);

insert into public.employees(employee_no,name,department,pin)
select 'EMP001','Demo Employee','Production','1234'
where not exists(select 1 from public.employees where employee_no='EMP001');
